[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stellalpha_vault = "64XogE2RvY7g4fDp8XxWZxFTycANjDK37n88GZizm5nx"

[programs.localnet]
stellalpha_vault = "64XogE2RvY7g4fDp8XxWZxFTycANjDK37n88GZizm5nx"
mock_swap = "DcVa1Kxo9DCUuvj6E8eJpUv9pARdGwWTM72MCT2vC3rS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
